### ISSUE TITLE
webpack issue

### ISSUE THREAD

**Issue by Johnny1102** [PeterStaev/nativescript-masked-text-field#11]
Hi,
I use nativescript-masked-text-field in my app. I need also use webpack to minify the app.

When I use this: 
`var maskedTextFieldMangleExcludes = require("nativescript-maskedTextField/uglify-mangle-excludes").default;`

The error below occurs. Do you know where can be a problem?
Thank you
```
module.js:487
    throw err;
    ^

Error: Cannot find module 'nativescript-maskedTextField/uglify-mangle-excludes'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/alpiq/Desktop/restore/app4lead/trunk/Alpiq.App4lead.Mobile/webpack.config.js:12:37)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
```

**Comment by PeterStaev** [comment]
Hey @Johnny1102 , this is because I mistyped the info in the readme 😄 The correct require is:
```js
var maskedTextFieldMangleExcludes = require("nativescript-masked-text-field/uglify-mangle-excludes").default;
```
