### ISSUE TITLE
Crash when spamming a masked textfield on Android

### ISSUE THREAD

**Issue by JBAndarelli** [PeterStaev/nativescript-masked-text-field#37]
On Android, when typing very fast in an already filled masked text input, it makes the app crash. Suppose you have an input like this :
```
    <MaskedTextField mask="99 99 99 99 99" keyboardType="phone"></MaskedTextField>
```
If you type in a valid number according to the mask, then try to add more numbers it will automatically delete them. But if you type in two numbers so that they appear in the field at the same before they get deleted it will crash the entire application.
```
ERROR LOG : 
System.err: com.tns.NativeScriptException: 
System.err: Calling js method run failed
System.err: 
System.err: Error: java.lang.IndexOutOfBoundsException: setSpan (20 ... 20) ends beyond length 19
System.err:     android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1309)
System.err:     android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
System.err:     android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
System.err:     android.text.Selection.setSelection(Selection.java:76)
System.err:     android.text.Selection.setSelection(Selection.java:87)
System.err:     android.widget.EditText.setSelection(EditText.java:127)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
System.err:     android.os.Handler.handleCallback(Handler.java:789)
System.err:     android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6541)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: File: "file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 155, column: 24
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-masked-text-field/masked-text-field.js', line: 79, column: 26
System.err: 	Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 421, column: 31
System.err: 	Frame: function:'Zone.runTask', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 188, column: 47
System.err: 	Frame: function:'ZoneTask.invokeTask', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 496, column: 34
System.err: 	Frame: function:'ZoneTask.invoke', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 485, column: 48
System.err: 	Frame: function:'timer', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1561, column: 29
System.err: 	Frame: function:'invoke', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err: 	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 388, column: 26
System.err: 	Frame: function:'Zone.runGuarded', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 151, column: 47
System.err: 	Frame: function:'', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 129, column: 29
System.err: 	Frame: function:'run', file:'file:///data/data/fr.makeeatup.makeeatup/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
System.err: 	at android.os.Handler.handleCallback(Handler.java:789)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: java.lang.IndexOutOfBoundsException: setSpan (20 ... 20) ends beyond length 19
System.err: 	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1309)
System.err: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:680)
System.err: 	at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:672)
System.err: 	at android.text.Selection.setSelection(Selection.java:76)
System.err: 	at android.text.Selection.setSelection(Selection.java:87)
System.err: 	at android.widget.EditText.setSelection(EditText.java:127)
System.err: 	... 14 more
```

**Comment by 18clans** [comment]
Ran into this bug on Android as well.  When you spam three+ numbers really fast it will crash the app.  I'm using version 4.0.1.

![textfield-mask-bug](https://user-images.githubusercontent.com/41965764/57798750-08f70080-7713-11e9-8c2d-ecd9e93ebbf6.gif)

**Comment by ghost** [comment]
did you solve? I have the same problem here.

**Comment by nik1st** [comment]
When it will be solved?

**Comment by PeterStaev** [comment]
Hey @NikStun , sadly I do not have much free time lately, so I cant give you any ETA.

**Comment by PeterStaev** [comment]
Hi guys, just to inform that the fix for this is available in the new version of the plugin available as part of [ProPlugins](https://proplugins.org).
